"Divorce.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1KAh1zfnxf1CyNttAKk43B5otW9Cad713
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sbn

df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset+based+on+uwb+for+clinical+establishments/divorce.csv")
#To import the data into a file and work on it

df.head()
#To view the data and understand it

df.tail()

df.info()
#to get the data types used in database

df.describe(
)
#To get a better understanding of the data

df.isnull()
#To see if any values is null or not

df.duplicated()
#To check if any values is repeated or not

comparison_result = df["income_man"]<= df["income_woman"]
#To select the values where

print(comparison_result)

true_values_df = df[comparison_result == True]
false_values_df = df[comparison_result == False]
#To select the values that are true and false separately

print(true_values_df)
print(false_values_df)

true_values_count = len(true_values_df)
false_values_count = len(false_values_df)
#To calculate the number of true values and the number of false values

print(true_values_count)
print(false_values_count)

categories = ['Women > Men', 'Men > Women']
counts = [true_values_count, false_values_count]

plt.barh(categories, counts, color=['blue', 'red'])

plt.xlabel('Number of Cases')
plt.title('Comparison of Salaries in Divorce Cases')

plt.show()
#To plot the graph of the corelation that we have found

from sklearn.model_selection import train_test_split
X = df.drop('divorce_date', axis=1)  # Features
y = df['divorce_date']  # Target variable

# Split the dataset into a training set (80%) and a test set (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)
