"""Planes.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1JLNPRv4JlC79w4dkQVBzJf7vwClNd--G
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sbn
#to be used for various functions

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset+based+on+uwb+for+clinical+establishments/planes.csv")
#to load the data into the notebook

df.head()
#to see the data (How it is set)

df.tail()
#to better understand the dataset

df.info()
#To check the data type of all the colums

df.describe()
#Dosent help much here just to know the mean.

df.duplicated()
#To check the repeated valuse

df.isnull()
# to see if there are any missing values

X = df[df['Dep_Time'].isnull()]
Y = df[df['Duration'].isnull()]

df = df.dropna(subset=['Dep_Time'])
df = df.dropna(subset=['Duration'])
#to remove the null values

df.isnull()

Airline_counts = df['Airline'].value_counts()
#To get the number of flights of each flights

print(Airline_counts)

labels = ['Jet Airways ', 'IndiGo', 'Air Asia', 'Multiple carriers','SpiceJet', 'Vistara', 'Air India', 'GoAir']
sizes = [3537, 1897, 296, 1097,745,438,1611,168]

plt.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=90, colors=['blue', 'green', 'orange', 'red'])

plt.title('Flight proportion per flight company')

plt.show()
#To make a pie chart

from sklearn.model_selection import train_test_split
feature = df.drop(['Airline','Duration','Price'], axis=1)
target = df['Price']
X_train, X_test, y_train, y_test = train_test_split(feature,target,test_size=0.2,random_state=42)
print("training set shape:",X_train.shape,y_train.shape)
print("testing set shape:",X_test.shape,y_test.shape)
