"""Unemployment.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1UYq1aMroWJjyD5UX-ntqDtoNEmMcZ-D9
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sbn
#to be used for various functions

#to read the file and get the data
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset+based+on+uwb+for+clinical+establishments/clean_unemployment.csv")

df.head()
#To view the data that we have just loaded

df.tail()
#To see the lower part of the data

df.info()
#To check all the Items and their data types

df.describe()
#To see if there is any corelation between any 2 columns

df.isnull()
#To check if there is any value missing

df.duplicated()
#To see I any values have been duplicated and remove them so that the data could yeild more accuracy

print(df.country_name)

df.set_index('country_name', inplace=True)
#To change the index from serial number to country name

df_reset = df.reset_index()
df['Average'] = df.mean(axis=1)
#To reset the index to original and and get the mean

plt.figure(figsize=(52, 30))

plt.barh(df.index, df['Average'], color='skyblue')

# Adding labels and title
plt.xlabel('Average Value Across Years')
plt.ylabel('Country')
plt.title('Average Value Across Years for Each Country')

plt.show()

data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset+based+on+uwb+for+clinical+establishments/clean_unemployment.csv")
#There was some issue in the database so I imported it again

from sklearn.model_selection import train_test_split
data.head()

features = data.drop(['country_code', 'country_name', 'continent'], axis=1)
target = data['continent']
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)
print("Training set shape:", X_train.shape, y_train.shape)
print("Testing set shape:", X_test.shape, y_test.shape)
